"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { useWorkspace } from "@/context/workspace-context";
import {
  formatDateWithTimezone,
  formatPrice,
  formatTimeWithTimezone,
} from "@/lib/formatters";

type Service = {
  id: number;
  name: string;
  price: string;
  duration: string | null;
  tag: string | null;
};

type Appointment = {
  id: number;
  client_name: string;
  service_price: number | null;
  status: string | null;
  appointment_at: string | null;
};

export default function ServiceDetailsPage() {
  const params = useParams();
  const serviceId = Number(params.id);

  const { workspaceSettings } = useWorkspace();

  const [service, setService] = useState<Service | null>(null);
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchServiceDetails() {
      setLoading(true);

      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user || !serviceId) {
        setLoading(false);
        return;
      }

      const [serviceRes, appointmentsRes] = await Promise.all([
        supabase
          .from("services")
          .select("*")
          .eq("id", serviceId)
          .eq("user_id", user.id)
          .single(),

        supabase
          .from("appointments")
          .select("*")
          .eq("service_id", serviceId)
          .eq("user_id", user.id)
          .order("appointment_at", { ascending: false }),
      ]);

      if (!serviceRes.error) {
        setService(serviceRes.data);
      }

      if (!appointmentsRes.error) {
        setAppointments(appointmentsRes.data || []);
      }

      setLoading(false);
    }

    fetchServiceDetails();
  }, [serviceId]);

  const totalRevenue = appointments.reduce((sum, appointment) => {
    return sum + (appointment.service_price || 0);
  }, 0);

  const confirmedAppointments = appointments.filter(
    (appointment) => appointment.status === "Confirmed"
  ).length;

  if (loading) {
    return (
      <section className="space-y-6">
        <div className="app-card h-[160px] animate-pulse" />
        <div className="grid gap-4 md:grid-cols-3">
          <div className="app-card h-[120px] animate-pulse" />
          <div className="app-card h-[120px] animate-pulse" />
          <div className="app-card h-[120px] animate-pulse" />
        </div>
      </section>
    );
  }

  if (!service) {
    return (
      <section className="space-y-6">
        <Link href="/services" className="app-button-secondary px-4 py-2">
          Back to Services
        </Link>

        <div className="app-card p-8 text-center">
          <p className="text-xl font-black">Service not found</p>
        </div>
      </section>
    );
  }

  return (
    <section className="space-y-7">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <Link href="/services" className="app-muted text-sm hover:text-white">
            ← Back to Services
          </Link>

          <p className="app-kicker mt-6">Service Profile</p>

          <h1 className="app-page-title mt-2">{service.name}</h1>

          <p className="app-muted mt-3">
            Service performance, bookings and revenue analytics.
          </p>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-3">
        <div className="app-accent-card p-6">
          <p className="text-sm font-bold uppercase tracking-[0.25em] text-black/50">
            Revenue
          </p>

          <h2 className="mt-3 text-5xl font-black">
            {formatPrice(
              totalRevenue.toString(),
              workspaceSettings?.currency
            )}
          </h2>

          <p className="mt-2 text-sm font-semibold">
            generated by this service
          </p>
        </div>

        <div className="app-card p-6">
          <p className="app-muted text-sm">Bookings</p>

          <h2 className="mt-3 text-5xl font-black">
            {appointments.length}
          </h2>

          <p className="app-muted mt-2 text-sm">
            {confirmedAppointments} confirmed
          </p>
        </div>

        <div className="app-card p-6">
          <p className="app-muted text-sm">Base Price</p>

          <h2 className="mt-3 text-4xl font-black">
            {formatPrice(service.price, workspaceSettings?.currency)}
          </h2>

          <p className="app-muted mt-2 text-sm">
            {service.duration || "No duration"}
          </p>
        </div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]">
        <div className="app-card p-6">
          <h2 className="app-section-title">Service Details</h2>

          <div className="mt-6 space-y-3">
            {[
              ["Name", service.name],
              ["Price", formatPrice(service.price, workspaceSettings?.currency)],
              ["Duration", service.duration],
              ["Tag", service.tag],
            ].map(([label, value]) => (
              <div
                key={label}
                className="app-card-dark flex items-center justify-between gap-4 px-5 py-4"
              >
                <p className="app-muted text-sm">{label}</p>
                <p className="text-right font-bold">{value || "Not set"}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="app-card p-6">
          <div className="mb-6">
            <h2 className="app-section-title">Appointment History</h2>

            <p className="app-muted mt-1 text-sm">
              All bookings linked to this service.
            </p>
          </div>

          <div className="space-y-4">
            {appointments.length === 0 ? (
              <div className="app-card-dark p-6 text-center">
                <p className="font-bold">No bookings yet</p>
              </div>
            ) : (
              appointments.map((appointment) => (
                <Link
                  key={appointment.id}
                  href={`/appointments/${appointment.id}`}
                  className="app-card-dark grid gap-4 px-5 py-4 transition hover:bg-white/[0.06] md:grid-cols-[0.9fr_1.2fr_0.8fr] md:items-center"
                >
                  <div>
                    <p className="font-black text-[var(--app-accent)]">
                      {formatTimeWithTimezone(
                        appointment.appointment_at,
                        workspaceSettings?.timezone
                      )}
                    </p>

                    <p className="app-muted mt-1 text-xs">
                      {formatDateWithTimezone(
                        appointment.appointment_at,
                        workspaceSettings?.timezone
                      )}
                    </p>
                  </div>

                  <div>
                    <p className="font-bold">
                      {appointment.client_name}
                    </p>

                    <p className="app-muted mt-1 text-sm">
                      {appointment.status || "No status"}
                    </p>
                  </div>

                  <p className="font-black text-[var(--app-accent)] md:text-right">
                    {appointment.service_price
                      ? formatPrice(
                          appointment.service_price.toString(),
                          workspaceSettings?.currency
                        )
                      : "No price"}
                  </p>
                </Link>
              ))
            )}
          </div>
        </div>
      </div>
    </section>
  );
}